sudo: false

language: scala
jdk:
  - oraclejdk8
  - oraclejdk9

env:
  - SBT_VERSION=1.0.2
  - SBT_VERSION=0.13.16

matrix:
  exclude:
    - jdk: oraclejdk9
      env: SBT_VERSION=0.13.16

script:
  - sbt ^^$SBT_VERSION scripted

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
