sudo: false

language: scala
jdk:
  - oraclejdk8
  - oraclejdk9

script:
  - sbt "scripted sbt-jooq/*"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.ivy2/cache -name "*-SNAPSHOT*" -delete
